### ISSUE TITLE
Replacing Sans-Serif font with Times-New-Roman equivalent

### ISSUE THREAD

**Issue by lucamuscat** [jp-um/university_of_malta_LaTeX_dissertation_template#11]
First of all, I would like that to thank you for the work that you put into this template.

I needed to change the font as I was finding the current one hard to read. I swapped it with the same font's Times-New-Roman counterpart by commenting out  [line 28 of um-fict.cls](https://github.com/jp-um/university_of_malta_LaTeX_dissertation_template/blob/25f24bde041053a9ccd2e8e01667459f646098ea/um-fict.cls#L28) and replacing all instances of `\sffamily` with `\rmfamily` (this was needed to update the sections and subsections font).

Do you happen to know if these changes will cause any edge cases or bugs in the formatting? If not, I would appreciate if the repo's readme included the steps needed to exact these changes.

**Comment by jp-um** [comment]
I added an FAQ here about this:
https://github.com/jp-um/university_of_malta_LaTeX_dissertation_template/tree/v2.6?tab=readme-ov-file#how-do-i-change-the-serif-to-sans-serif-typeface-or-vice-versa

Kindly note that I have removed the FICT template and am only maintaining one template now
