### ISSUE TITLE
when using two columns layout, the captions do not follow

### ISSUE THREAD

**Issue by RandomLambda** [jp-um/university_of_malta_LaTeX_dissertation_template#13]
changing 
\usepackage[width=.95\textwidth]{caption} % set the width of the captions
to 
\usepackage[width=.95\linewidth]{caption} % set the width of the captions

in the file:
um.cls
does fix this, without impacting single column layout.

**Comment by jp-um** [comment]
Sorry for the delay in getting back to you (I did not have notifications switched on for this repo (doh!).

What do you mean with _single column layout_? There is no single (or two column) layout in this template.

I do not think that a dissertation is meant to be typeset in columns (this is not a paper).

**Comment by RandomLambda** [comment]
no worries

I agree, I have never seen a thesis is two column layout, nor does this template come with one/twocolumn layout. 
I simply meant using \onecolumn or \twocolumn at the start (or end) of the two-column part of the document. 

Reason being that after I used this template for my bachelor's thesis, I started using this same template also for other uses, such as project reports, simply because it is so stable, versatile, and pretty. Figured others might be doing the same. 
(In that project report I reduced the font size, and those blocks of text started to look weird, especially if you add an image, with so much empty space around it.)

**Comment by jp-um** [comment]
I can imagine that if you add those LaTeX directives you would need to change a lot of other parameters in a book template such as this (and `memoir` which is the underlying class).

I am going to close this issue.  Thanks for getting in touch.
