### ISSUE TITLE
How to stop resetting the footnote numbering per chapter?

### ISSUE THREAD

**Issue by juliafalcao** [jp-um/university_of_malta_LaTeX_dissertation_template#14]
Hi! I'm using this template for my master's thesis, and I've noticed that the footnote numbering restarts every chapter, but my supervisor recommended that I keep the numbering continuous throughout the thesis. How could I change this to stop the numbering from restarting at every chapter?

**Comment by jp-um** [comment]
Sorry for the delay in getting back to you (I did not have notifications switched on for this repo (doh!).

Anyways, I added an FAQ entry on how to do this (one line change)
https://github.com/jp-um/university_of_malta_LaTeX_dissertation_template?tab=readme-ov-file#how-do-i-make-continuous-footnote-numbers
