### ISSUE TITLE
Deadly sins url not working

### ISSUE THREAD

**Issue by leonlan** [jp-um/university_of_malta_LaTeX_dissertation_template#2]
The link of the _Deadly sins_ url is outdated. Since the PDF seems to be hosted on mirrors, I suggest adding the CTAN url https://ctan.org/tex-archive/info/l2tabu/english/?lang=en instead of a direct link to the PDF.

https://github.com/jp-um/university_of_malta_LaTeX_dissertation_template/blob/a297ad70efbcdcad690575c31bf2a8d910a0679c/dissertation_main.tex#L11

**Comment by leonlan** [comment]
Actually I believe this link could work: http://mirrors.ctan.org/info/l2tabu/english/l2tabuen.pdf

**Comment by jp-um** [comment]
Thanks, fixed this as suggested!
