### ISSUE TITLE
Adding chap#/ subdirectories to images/

### ISSUE THREAD

**Issue by leonlan** [jp-um/university_of_malta_LaTeX_dissertation_template#3]
Quoting point 8 from your post on [LaTeX Tips:](https://bitsilla.com/blog/2019/01/latex-tips-for-your-dissertation-or-project-write-up/)

> 8. Figures should go under subdirectory images in the root folder.  Here, too, you should use subdirectories for each chapter to organize your work

**Comment by leonlan** [comment]
I see that the current template holds `images/` subdirectories in `chap#/`, e.g. `chap#/images/`. Is this preferred?

**Comment by jp-um** [comment]
Hi Leon, this is somewhat controversial (and straightforward to fix).  I think of each chapter as a standalone thing, so I like to have all the code/images/include files under the respective chap# directory.  Others use generic "images" in root and subdir with the chap# (as suggested by yourself).  Up to you really but ...

The images directory you see in the root should **only** contain the images OF THE TEMPLATE (and not of the chaps, which are logically placed inside each chapter dir).

You want to change line 65 in `dissertation_main.tex`

`\graphicspath{{./images/}{./chap1/images/}{./chap2/images/}} `
