### ISSUE TITLE
Change references style to IEEETR

### ISSUE THREAD

**Issue by DheerendraTomar** [jp-um/university_of_malta_LaTeX_dissertation_template#5]
Hi J,

First of all, thank you for this amazing LaTeX template. I have one issue: 

1. I have changed the references style to IEEETR from UM-PLAINNAT in order to use the references like : This figure is taken from [x]. 

References
[x] This is the references I was referring to. 

but the issue is the reference in the text show like: This figure is taken from (x) instead of [x].

Thanks,
D

**Comment by jp-um** [comment]
In a sentence, like your example, the reference should not have brackets around it -- as the reference is actually part of the sentence (and not a reference per se).

In this case, you should use `\citet{myref}` (instead of `\citep{myref}`).

**Comment by DheerendraTomar** [comment]
Thank you. But, it's not working as expected. It is still using these '( )' brackets instead of '[ ]'. I am also getting another error : 
Package natbib Error: Bibliography not compatible with author-year citations. ...and\NAT@force@numbers{}\NAT@force@numbers

**Comment by jp-um** [comment]
can you send me a minimal working example please?  So I can try it out.

[An example here](https://github.com/jp-um/university_of_malta_LaTeX_dissertation_template/blob/deccb1b93de9b96da07da91a306a09c4a5c8fbf7/chap1/introduction_main.tex#L27)

**Comment by DheerendraTomar** [comment]
Sure! here it is.

.bib file - content (file is attached at the end)

@Misc{DUMMY:1,
  author = {Christine Belcastro and John Foster},
  title  = {Aircraft Loss-of-Control Accident Analysis},
  year   = {2010},
  doi    = {10.2514/6.2010-8004},
}

Some random text \cite{DUMMY:1}. 

output:

![image](https://user-images.githubusercontent.com/26894057/125603752-c62f520b-5db9-428b-b0c7-04903ad3b37c.png)

if I do \citet{DUMMY:1} then I have output like this:

![image](https://user-images.githubusercontent.com/26894057/125603917-c66585c6-bb49-4812-939e-d1a88707bc6d.png)


And to my surprise when I checked the references section at the end of the document. It doesn't show that DUMMY:1 reference, instead it shows the one which you provided.

![image](https://user-images.githubusercontent.com/26894057/125604181-e0073cc9-f7b7-4493-bac0-1840a57e8b1f.png)


I get one error when I compile and view the file which is:
![image](https://user-images.githubusercontent.com/26894057/125604853-43e2a729-1af5-4f49-8785-2c59d004665c.png)


I am attaching the .bib file which was generated with JabRef.
[introduction_biblio.zip](https://github.com/jp-um/university_of_malta_LaTeX_dissertation_template/files/6815252/introduction_biblio.zip)

**Comment by DheerendraTomar** [comment]
I have managed to solve the issue. Closing this thread.
